version: '3'

services:
  biblioteca-only:
    image: bitnami/postgresql
    ports:
      - 5430:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=biblioteca